alias free="free -m"
alias update="sudo aptitude update"
alias install="sudo aptitude install"
alias upgrade="sudo aptitude safe-upgrade"
alias remove="sudo aptitude remove"
source ~/.work_aliases
alias mong="felix && thin start"
alias svnr="svn status -uv 2>/dev/null | egrep '^([^\? ]|       \*)'"
alias svnc="svn status | grep '^C'"
alias ci="svn commit" 
alias diff="colordiff" 
alias mysqlb="sudo mysql-query-browser &"
alias firefoxd="firefox -P developer -NO-REMOTE &"
alias gvim="gvim . &"
alias sup="svn update"
alias rlc="felix && rake log:clear"
alias lessd="felix && less -n -R log/development.log"
alias less="less -R"
alias c="cheat"
alias off="sudo apache2ctl stop"
alias on="sudo apache2ctl start"
alias ares="sudo apache2ctl restart"
alias this="felix && thin start"
alias ichr="ssh anil@icanhasruby.com"
alias die="sudo killall"
alias conns='sudo lsof -i'
alias rb='railsbench'
alias editaliases='cd ~ && vim ~/.bash_aliases'
alias remove_tmp="rm -rf \`find . -name *.tmp\`"
alias tun="rtunnel_client -c icanhasruby.com -f 4000 -t localhost:3000"
alias send_emails="rake utils:send_emails SKIP_SERVER_INIT=Y"
alias daily_task="rake utils:daily_task SKIP_SERVER_INIT=Y"
alias hourly_task="rake utils:hourly_task SKIP_SERVER_INIT=Y"

